import { Preset, FilterSettings } from '../types/studio';

export const DEFAULT_FILTER_SETTINGS: FilterSettings = {
  image: {
    opacity: 100,
    blendMode: 'normal',
  },
  gradient: {
    enabled: true,
    type: 'mesh',
    blendMode: 'overlay',
    opacity: 75,
    angle: 135,
    stops: [
      { id: '1', color: '#00d2ff', position: 0 },
      { id: '2', color: '#9d00ff', position: 35 },
      { id: '3', color: '#ff007f', position: 70 },
      { id: '4', color: '#ff7a00', position: 100 },
    ],
    meshColors: ['#00d2ff', '#9d00ff', '#ff007f', '#ff7a00'],
    position: 'overlay',
  },
  blur: {
    enabled: false,
    category: 'mesh',
    radius: 45, // 75%
    angle: 45,
    focalSize: 40,
    glassFrost: 65,
    glassSpecular: 80,
    tiltPosition: 50,
    tiltWidth: 35,
  },
  noise: {
    enabled: true,
    type: 'film',
    amount: 15,
    monochrome: false,
    blendMode: 'overlay',
  },
  patterns: {
    enabled: true,
    type: 'lightning',
    scale: 65,
    opacity: 95,
    color: '#00f0ff',
    backgroundColor: 'transparent',
    strokeWidth: 1.5,
    rotation: 0,
    offsetX: 0,
    offsetY: 0,
    glow: 0,
    blendMode: 'screen',
    position: 'overlay',
    is3D: false,
    depth3D: 15,
    pitch3D: 25,
    yaw3D: 0,
    lightAngle3D: 135,
    shading3D: 'extrude',
    fullFill: true,
    fillMode: 'both',
    fillOpacity: 45,
    patternize: false,
    patternizeMode: 'mosaic',
    patternizeFidelity: 75,
    patternizeContrast: 50,
    patternizeInvert: false,
  },
  fractalGlass: {
    enabled: false,
    mode: '1',
    distortion: 40,
    dispersion: 35,
    scale: 30,
    frost: 20,
    specular: 50,
    angle: 90,
    blendMode: 'normal',
    opacity: 100,
  },
  gradientMaker: {
    enabled: false,
    mode: '1',
    mapPalettePreset: 'cyberpunk',
    stops: [
      { id: '1', color: '#00d2ff', position: 0 },
      { id: '2', color: '#9d00ff', position: 50 },
      { id: '3', color: '#ff007f', position: 100 },
    ],
    angle: 135,
    meshColors: ['#00d2ff', '#9d00ff', '#ff007f', '#ff7a00'],
    blendMode: 'overlay',
    opacity: 85,
    position: 'overlay',
  },
  upscale: {
    factor: 8,
    sharpen: 30,
    format: 'image/png',
    quality: 0.95,
  },
};

export const CREATIVE_PRESETS: Preset[] = [
  {
    id: 'cyberpunk-neon',
    name: 'Cyberpunk Neon',
    description: 'Electric violet & cyan gradient, chromatic aberration, digital noise.',
    badge: 'Trending',
    settings: {
      gradient: {
        enabled: true,
        type: 'linear',
        blendMode: 'overlay',
        opacity: 70,
        angle: 135,
        stops: [
          { id: '1', color: '#7928ca', position: 0 },
          { id: '2', color: '#ff0080', position: 50 },
          { id: '3', color: '#00dfd8', position: 100 },
        ],
        meshColors: ['#7928ca', '#00dfd8', '#ff0080', '#10b981'],
      },
      blur: {
        enabled: true,
        category: 'glass',
        radius: 22,
        angle: 45,
        focalSize: 35,
        glassFrost: 75,
        glassSpecular: 90,
        tiltPosition: 50,
        tiltWidth: 30,
      },
      noise: {
        enabled: true,
        type: 'digital',
        amount: 32,
        monochrome: false,
        blendMode: 'overlay',
      },
      patterns: {
        enabled: true,
        type: 'isometric',
        scale: 45,
        opacity: 25,
        color: '#00dfd8',
        blendMode: 'screen',
      },
      upscale: {
        factor: 2,
        sharpen: 35,
        format: 'image/png',
        quality: 0.95,
      },
    },
  },
  {
    id: 'frosted-glass',
    name: 'Frosted Glassmorphism',
    description: 'Ultra-smooth blurred glass sheen, chromatic dispersion rim.',
    badge: 'Pro UI',
    settings: {
      gradient: {
        enabled: true,
        type: 'mesh',
        blendMode: 'soft-light',
        opacity: 45,
        angle: 45,
        stops: [
          { id: '1', color: '#ffffff', position: 0 },
          { id: '2', color: '#a78bfa', position: 100 },
        ],
        meshColors: ['#ffffff', '#60a5fa', '#a78bfa', '#f472b6'],
      },
      blur: {
        enabled: true,
        category: 'glass',
        radius: 28,
        angle: 90,
        focalSize: 50,
        glassFrost: 85,
        glassSpecular: 95,
        tiltPosition: 50,
        tiltWidth: 30,
      },
      noise: {
        enabled: true,
        type: 'film',
        amount: 14,
        monochrome: true,
        blendMode: 'soft-light',
      },
      patterns: {
        enabled: false,
        type: 'none',
        scale: 25,
        opacity: 15,
        color: '#ffffff',
        blendMode: 'overlay',
      },
      upscale: {
        factor: 1,
        sharpen: 15,
        format: 'image/png',
        quality: 0.95,
      },
    },
  },
  {
    id: 'golden-hour-mesh',
    name: 'Golden Hour Glow',
    description: '4-point warm amber, peach & coral mesh with soft focal radial blur.',
    badge: 'Warm',
    settings: {
      gradient: {
        enabled: true,
        type: 'mesh',
        blendMode: 'overlay',
        opacity: 60,
        angle: 90,
        stops: [
          { id: '1', color: '#f59e0b', position: 0 },
          { id: '2', color: '#f43f5e', position: 100 },
        ],
        meshColors: ['#fbbf24', '#f87171', '#fb923c', '#e11d48'],
      },
      blur: {
        enabled: true,
        category: 'radial',
        radius: 16,
        angle: 0,
        focalSize: 45,
        glassFrost: 40,
        glassSpecular: 50,
        tiltPosition: 50,
        tiltWidth: 30,
      },
      noise: {
        enabled: true,
        type: 'film',
        amount: 20,
        monochrome: false,
        blendMode: 'soft-light',
      },
      patterns: {
        enabled: false,
        type: 'none',
        scale: 30,
        opacity: 20,
        color: '#fbbf24',
        blendMode: 'overlay',
      },
      upscale: {
        factor: 2,
        sharpen: 25,
        format: 'image/jpeg',
        quality: 0.92,
      },
    },
  },
  {
    id: 'vintage-noir',
    name: '35mm Film Noir',
    description: 'Monochromatic retro grain, dust flecks, directional gradient falloff.',
    badge: 'Retro',
    settings: {
      gradient: {
        enabled: true,
        type: 'linear',
        blendMode: 'multiply',
        opacity: 35,
        angle: 180,
        stops: [
          { id: '1', color: '#111827', position: 0 },
          { id: '2', color: '#374151', position: 100 },
        ],
        meshColors: ['#1f2937', '#111827', '#4b5563', '#000000'],
      },
      blur: {
        enabled: true,
        category: 'tiltshift',
        radius: 20,
        angle: 0,
        focalSize: 40,
        glassFrost: 30,
        glassSpecular: 30,
        tiltPosition: 50,
        tiltWidth: 40,
      },
      noise: {
        enabled: true,
        type: 'retro',
        amount: 45,
        monochrome: true,
        blendMode: 'overlay',
      },
      patterns: {
        enabled: false,
        type: 'none',
        scale: 30,
        opacity: 20,
        color: '#ffffff',
        blendMode: 'overlay',
      },
      upscale: {
        factor: 1,
        sharpen: 30,
        format: 'image/jpeg',
        quality: 0.9,
      },
    },
  },
  {
    id: 'mathematical-fractal',
    name: 'Quantum Julia Fractal',
    description: 'Iterative Mandelbrot & Julia fractal synthesis with angular blur.',
    badge: 'Math Art',
    settings: {
      gradient: {
        enabled: true,
        type: 'conical',
        blendMode: 'screen',
        opacity: 55,
        angle: 60,
        stops: [
          { id: '1', color: '#8b5cf6', position: 0 },
          { id: '2', color: '#3b82f6', position: 33 },
          { id: '3', color: '#10b981', position: 66 },
          { id: '4', color: '#8b5cf6', position: 100 },
        ],
        meshColors: ['#8b5cf6', '#3b82f6', '#10b981', '#ec4899'],
      },
      blur: {
        enabled: true,
        category: 'angular',
        radius: 15,
        angle: 45,
        focalSize: 50,
        glassFrost: 50,
        glassSpecular: 50,
        tiltPosition: 50,
        tiltWidth: 30,
      },
      noise: {
        enabled: true,
        type: 'digital',
        amount: 18,
        monochrome: false,
        blendMode: 'overlay',
      },
      patterns: {
        enabled: true,
        type: 'julia',
        scale: 60,
        opacity: 65,
        color: '#c084fc',
        blendMode: 'screen',
      },
      upscale: {
        factor: 2,
        sharpen: 40,
        format: 'image/png',
        quality: 0.95,
      },
    },
  },
];
