import { DesignRecipe, DEFAULT_TRANSFORM, DEFAULT_ADJUSTMENTS } from '../../types/project';

export interface TemplateCategory {
  id: string;
  name: string;
  count: number;
}

export const TEMPLATE_CATEGORIES: TemplateCategory[] = [
  { id: 'all', name: 'All Templates', count: 18 },
  { id: 'social', name: 'Social Media & YouTube', count: 4 },
  { id: 'wallpaper', name: '4K & HD Wallpapers', count: 4 },
  { id: 'tech', name: 'Cyberpunk & Sci-Fi Tech', count: 3 },
  { id: 'luxury', name: 'Luxury Gold & Minimal', count: 3 },
  { id: 'glass', name: 'Glassmorphism & Neon', count: 4 },
];

export const DESIGN_TEMPLATES: DesignRecipe[] = [
  // 1. Cyberpunk Neon Aurora
  {
    id: 'tmpl_cyberpunk_aurora',
    name: 'Cyberpunk Neon Aurora',
    category: 'tech',
    tags: ['cyberpunk', 'neon', 'glow', 'aurora'],
    width: 1920,
    height: 1080,
    background: {
      type: 'color',
      color: '#070913',
    },
    layers: [
      {
        name: 'Electric Mesh Gradient',
        type: 'gradient',
        visible: true,
        locked: false,
        opacity: 85,
        blendMode: 'screen',
        transform: { ...DEFAULT_TRANSFORM, width: 1920, height: 1080 },
        order: 0,
        gradientType: 'mesh',
        angle: 45,
        stops: [
          { id: '1', color: '#00f0ff', position: 0 },
          { id: '2', color: '#7928ca', position: 50 },
          { id: '3', color: '#ff0080', position: 100 },
        ],
        meshColors: ['#00f0ff', '#7928ca', '#ff0080', '#050518'],
      },
      {
        name: 'Cyber Circuit Grid',
        type: 'pattern',
        visible: true,
        locked: false,
        opacity: 60,
        blendMode: 'overlay',
        transform: { ...DEFAULT_TRANSFORM, width: 1920, height: 1080 },
        order: 1,
        patternType: 'pat_tech_001',
        scale: 45,
        rotation: 0,
        offsetX: 0,
        offsetY: 0,
        spacing: 20,
        density: 50,
        strokeWidth: 1.5,
        strokeOpacity: 80,
        fillOpacity: 20,
        color: '#00f0ff',
        glow: 8,
        glowColor: '#00f0ff',
        fullFill: true,
        fillMode: 'both',
      },
      {
        name: 'Vortex Neon Glow',
        type: 'glow',
        visible: true,
        locked: false,
        opacity: 90,
        blendMode: 'screen',
        transform: { ...DEFAULT_TRANSFORM, width: 1920, height: 1080 },
        order: 2,
        glowType: 'bloom',
        intensity: 85,
        radius: 120,
        spread: 60,
        color: '#ff0080',
      },
      {
        name: '35mm Film Grain',
        type: 'noise',
        visible: true,
        locked: false,
        opacity: 35,
        blendMode: 'overlay',
        transform: { ...DEFAULT_TRANSFORM, width: 1920, height: 1080 },
        order: 3,
        noiseType: 'film',
        amount: 22,
        monochrome: true,
        scale: 100,
        contrast: 50,
      },
    ],
  },

  // 2. Prismatic Holographic Glass
  {
    id: 'tmpl_prismatic_glass',
    name: 'Prismatic Holographic Glass',
    category: 'glass',
    tags: ['hologram', 'glassmorphism', 'dispersion', 'refraction'],
    width: 1920,
    height: 1080,
    background: {
      type: 'color',
      color: '#080a12',
    },
    layers: [
      {
        name: 'Conic Hologram Flow',
        type: 'gradient',
        visible: true,
        locked: false,
        opacity: 90,
        blendMode: 'normal',
        transform: { ...DEFAULT_TRANSFORM, width: 1920, height: 1080 },
        order: 0,
        gradientType: 'conical',
        angle: 120,
        stops: [
          { id: '1', color: '#03071e', position: 0 },
          { id: '2', color: '#3730a3', position: 25 },
          { id: '3', color: '#a855f7', position: 50 },
          { id: '4', color: '#38bdf8', position: 75 },
          { id: '5', color: '#ffffff', position: 100 },
        ],
        meshColors: ['#03071e', '#3730a3', '#a855f7', '#38bdf8'],
      },
      {
        name: 'Sacred Arabesque Matrix',
        type: 'pattern',
        visible: true,
        locked: false,
        opacity: 50,
        blendMode: 'overlay',
        transform: { ...DEFAULT_TRANSFORM, width: 1920, height: 1080 },
        order: 1,
        patternType: 'pat_sacred_001',
        scale: 60,
        rotation: 45,
        offsetX: 0,
        offsetY: 0,
        spacing: 25,
        density: 60,
        strokeWidth: 2,
        strokeOpacity: 90,
        fillOpacity: 25,
        color: '#ffffff',
        fullFill: true,
        fillMode: 'both',
      },
      {
        name: 'Fractal Ribs Glass',
        type: 'glass',
        visible: true,
        locked: false,
        opacity: 80,
        blendMode: 'normal',
        transform: { ...DEFAULT_TRANSFORM, width: 1920, height: 1080 },
        order: 2,
        settings: {
          enabled: true,
          mode: '1',
          distortion: 45,
          dispersion: 60,
          scale: 35,
          frost: 20,
          specular: 70,
          angle: 35,
          blendMode: 'normal',
          opacity: 80,
        },
      },
    ],
  },

  // 3. YouTube Thumbnail Bold Hero
  {
    id: 'tmpl_youtube_bold',
    name: 'YouTube Hero Thumbnail',
    category: 'social',
    tags: ['youtube', 'thumbnail', 'bold', 'creator'],
    width: 1280,
    height: 720,
    background: {
      type: 'color',
      color: '#0f0728',
    },
    layers: [
      {
        name: 'Radial Sunset Blast',
        type: 'gradient',
        visible: true,
        locked: false,
        opacity: 100,
        blendMode: 'normal',
        transform: { ...DEFAULT_TRANSFORM, width: 1280, height: 720 },
        order: 0,
        gradientType: 'radial',
        angle: 0,
        stops: [
          { id: '1', color: '#ff7a00', position: 0 },
          { id: '2', color: '#ff007f', position: 55 },
          { id: '3', color: '#3b0764', position: 100 },
        ],
        meshColors: ['#ff7a00', '#ff007f', '#7928ca', '#00f0ff'],
      },
      {
        name: 'Dynamic Halftone Stipple',
        type: 'pattern',
        visible: true,
        locked: false,
        opacity: 45,
        blendMode: 'overlay',
        transform: { ...DEFAULT_TRANSFORM, width: 1280, height: 720 },
        order: 1,
        patternType: 'pat_halftone_005',
        scale: 35,
        rotation: 15,
        offsetX: 0,
        offsetY: 0,
        spacing: 15,
        density: 70,
        strokeWidth: 2,
        strokeOpacity: 100,
        fillOpacity: 40,
        color: '#ffffff',
        fullFill: true,
        fillMode: 'both',
      },
      {
        name: 'Catchy Title Text',
        type: 'text',
        visible: true,
        locked: false,
        opacity: 100,
        blendMode: 'normal',
        transform: { ...DEFAULT_TRANSFORM, x: 80, y: 260, width: 1120, height: 200 },
        order: 2,
        text: 'GRADIENT X\nSTUDIO PRO',
        fontFamily: 'system-ui, sans-serif',
        fontSize: 84,
        fontWeight: 900,
        lineHeight: 1.05,
        letterSpacing: -1,
        color: '#ffffff',
        align: 'left',
        shadowBlur: 25,
        shadowColor: 'rgba(0,0,0,0.85)',
        shadowOffsetX: 0,
        shadowOffsetY: 8,
      },
    ],
  },

  // 4. Luxury Emerald & Gold Wallpaper
  {
    id: 'tmpl_luxury_emerald',
    name: 'Luxury Emerald & Gold',
    category: 'luxury',
    tags: ['luxury', 'emerald', 'gold', 'minimal'],
    width: 3840,
    height: 2160,
    background: {
      type: 'color',
      color: '#021812',
    },
    layers: [
      {
        name: 'Emerald Deep Gradient',
        type: 'gradient',
        visible: true,
        locked: false,
        opacity: 95,
        blendMode: 'normal',
        transform: { ...DEFAULT_TRANSFORM, width: 3840, height: 2160 },
        order: 0,
        gradientType: 'linear',
        angle: 135,
        stops: [
          { id: '1', color: '#022c22', position: 0 },
          { id: '2', color: '#065f46', position: 50 },
          { id: '3', color: '#047857', position: 100 },
        ],
        meshColors: ['#022c22', '#065f46', '#10b981', '#fbbf24'],
      },
      {
        name: 'Gold Geometric Hexagons',
        type: 'pattern',
        visible: true,
        locked: false,
        opacity: 70,
        blendMode: 'screen',
        transform: { ...DEFAULT_TRANSFORM, width: 3840, height: 2160 },
        order: 1,
        patternType: 'pat_geometric_001',
        scale: 50,
        rotation: 0,
        offsetX: 0,
        offsetY: 0,
        spacing: 30,
        density: 50,
        strokeWidth: 2.2,
        strokeOpacity: 90,
        fillOpacity: 15,
        color: '#fbbf24',
        glow: 10,
        glowColor: '#f59e0b',
        fullFill: true,
        fillMode: 'both',
      },
      {
        name: 'Warm Ambient Light',
        type: 'glow',
        visible: true,
        locked: false,
        opacity: 75,
        blendMode: 'soft-light',
        transform: { ...DEFAULT_TRANSFORM, width: 3840, height: 2160 },
        order: 2,
        glowType: 'soft-light',
        intensity: 65,
        radius: 180,
        spread: 80,
        color: '#fef08a',
      },
    ],
  },

  // 5. Instagram Story Fluid Vibe
  {
    id: 'tmpl_instagram_story',
    name: 'Instagram Story Fluid Vibe',
    category: 'social',
    tags: ['instagram', 'story', '9:16', 'fluid', 'pastel'],
    width: 1080,
    height: 1920,
    background: {
      type: 'color',
      color: '#1a0b2e',
    },
    layers: [
      {
        name: 'Vertical Aurora Mesh',
        type: 'gradient',
        visible: true,
        locked: false,
        opacity: 100,
        blendMode: 'normal',
        transform: { ...DEFAULT_TRANSFORM, width: 1080, height: 1920 },
        order: 0,
        gradientType: 'mesh',
        angle: 90,
        stops: [
          { id: '1', color: '#ff007f', position: 0 },
          { id: '2', color: '#7928ca', position: 50 },
          { id: '3', color: '#00d2ff', position: 100 },
        ],
        meshColors: ['#ff007f', '#7928ca', '#00d2ff', '#4cd137'],
      },
      {
        name: 'Japanese Ocean Waves',
        type: 'pattern',
        visible: true,
        locked: false,
        opacity: 55,
        blendMode: 'overlay',
        transform: { ...DEFAULT_TRANSFORM, width: 1080, height: 1920 },
        order: 1,
        patternType: 'pat_japanese_003',
        scale: 45,
        rotation: 0,
        offsetX: 0,
        offsetY: 0,
        spacing: 20,
        density: 60,
        strokeWidth: 2,
        strokeOpacity: 85,
        fillOpacity: 25,
        color: '#ffffff',
        fullFill: true,
        fillMode: 'both',
      },
      {
        name: 'Frosted Glass Center Card',
        type: 'shape',
        visible: true,
        locked: false,
        opacity: 85,
        blendMode: 'normal',
        transform: { ...DEFAULT_TRANSFORM, x: 90, y: 560, width: 900, height: 800 },
        order: 2,
        shapeType: 'rectangle',
        fillColor: 'rgba(255, 255, 255, 0.08)',
        fillOpacity: 60,
        strokeColor: 'rgba(255, 255, 255, 0.25)',
        strokeWidth: 1.5,
        strokeOpacity: 80,
        cornerRadius: 36,
      },
    ],
  },
];
