import * as THREE from 'three';
import { GLTFExporter } from 'three/examples/jsm/exporters/GLTFExporter.js';
import { LumberStackParams } from './lumberModelGenerator';

/**
 * Downloads a text or binary blob as a named file in the browser
 */
export function downloadFile(content: BlobPart, filename: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

/**
 * Exports a Three.js Group or Mesh to Wavefront .OBJ format
 */
export function exportGroupToOBJ(group: THREE.Group, filename: string = 'lumber_stack_3d.obj'): string {
  let output = `# Wavefront OBJ File generated by Gradient X Studio 3D Engine\n`;
  output += `# Object Name: ${group.name || 'LumberStack'}\n\n`;

  let vertexOffset = 1;
  let normalOffset = 1;
  let uvOffset = 1;

  group.updateMatrixWorld(true);

  group.traverse(child => {
    if (child instanceof THREE.Mesh && child.geometry) {
      const geom = child.geometry.clone();
      geom.applyMatrix4(child.matrixWorld);

      const posAttr = geom.getAttribute('position');
      const normAttr = geom.getAttribute('normal');
      const uvAttr = geom.getAttribute('uv');
      const index = geom.getIndex();

      if (!posAttr) return;

      output += `o Mesh_${child.id}\n`;

      // Vertices
      for (let i = 0; i < posAttr.count; i++) {
        output += `v ${posAttr.getX(i).toFixed(4)} ${posAttr.getY(i).toFixed(4)} ${posAttr.getZ(i).toFixed(4)}\n`;
      }

      // UVs
      if (uvAttr) {
        for (let i = 0; i < uvAttr.count; i++) {
          output += `vt ${uvAttr.getX(i).toFixed(4)} ${uvAttr.getY(i).toFixed(4)}\n`;
        }
      }

      // Normals
      if (normAttr) {
        for (let i = 0; i < normAttr.count; i++) {
          output += `vn ${normAttr.getX(i).toFixed(4)} ${normAttr.getY(i).toFixed(4)} ${normAttr.getZ(i).toFixed(4)}\n`;
        }
      }

      // Faces
      if (index) {
        for (let i = 0; i < index.count; i += 3) {
          const a = index.getX(i) + vertexOffset;
          const b = index.getX(i + 1) + vertexOffset;
          const c = index.getX(i + 2) + vertexOffset;

          if (uvAttr && normAttr) {
            const uva = index.getX(i) + uvOffset;
            const uvb = index.getX(i + 1) + uvOffset;
            const uvc = index.getX(i + 2) + uvOffset;

            const na = index.getX(i) + normalOffset;
            const nb = index.getX(i + 1) + normalOffset;
            const nc = index.getX(i + 2) + normalOffset;

            output += `f ${a}/${uva}/${na} ${b}/${uvb}/${nb} ${c}/${uvc}/${nc}\n`;
          } else {
            output += `f ${a} ${b} ${c}\n`;
          }
        }
      } else {
        for (let i = 0; i < posAttr.count; i += 3) {
          const a = i + vertexOffset;
          const b = i + 1 + vertexOffset;
          const c = i + 2 + vertexOffset;
          output += `f ${a} ${b} ${c}\n`;
        }
      }

      vertexOffset += posAttr.count;
      if (normAttr) normalOffset += normAttr.count;
      if (uvAttr) uvOffset += uvAttr.count;

      geom.dispose();
    }
  });

  return output;
}

/**
 * Exports a Three.js Group or Mesh to GLTF JSON format
 */
export async function exportGroupToGLTF(group: THREE.Group, filename: string = 'lumber_stack_3d.gltf'): Promise<void> {
  const exporter = new GLTFExporter();
  return new Promise((resolve, reject) => {
    exporter.parse(
      group,
      gltf => {
        const output = JSON.stringify(gltf, null, 2);
        downloadFile(output, filename, 'application/json');
        resolve();
      },
      error => {
        console.error('GLTF export error:', error);
        reject(error);
      },
      { binary: false }
    );
  });
}
